name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python 3.8
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set Up Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        sudo apt-get -yqq install chromium-chromedriver
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --junit-xml=junit/test-results.xml